name: ReleaseFilter
version: 0
author: moderator_man
main: com.oldschoolminecraft.rf.ReleaseFilter
depend: [Spout, PermissionsEx]
commands:
  rf:
    description: ReleaseFilter command
    usage: /rf <allow/deny/help> [username]